### ISSUE TITLE
Diplay actual electrons per shell

### ISSUE THREAD

**Issue by nihey** [nihey/breaking-badify#11]
We are currently displaying the `electron configuration` on the show's `electron per shell` field. We should do this 'back-to-school' [conversion](https://en.wikipedia.org/wiki/Electron_configurations_of_the_elements_%28data_page%29).

**Comment by BrOrlandi** [comment]
That's why the logo shows "-1 +1 +5" in "Br" and ours show more values?

**Comment by nihey** [comment]
No, that would be [Bromine](https://en.wikipedia.org/wiki/Bromine) oxidation states. It's funny because it seems that ours is actually correct.

The electron per shell issue is refers to displaying `[Ar] 3d10 4s2 4p5` instead of `2-8-18-7`
