### ISSUE TITLE
First letter is turning lower case

### ISSUE THREAD

**Issue by BrOrlandi** [nihey/breaking-badify#6]
![screenshot from 2015-07-05 20 22 45](https://cloud.githubusercontent.com/assets/1594658/8513897/9e72a9ec-2353-11e5-8db1-9311471845c0.png)

**Comment by nihey** [comment]
Should it be upper case? By default i was maintaining everything but the element letters at lower case. I can change that if you don't like it.

**Comment by BrOrlandi** [comment]
I prefer the string typed should not be modified. So it should be upper case if the first letter is uppercase or lower if it is.
