### ISSUE TITLE
Facebook and Twitter like, share buttons. Github star button.

### ISSUE THREAD

**Issue by BrOrlandi** [nihey/breaking-badify#8]
Facebook Like Button
Facebook Share Button (Share the URL with Breaking Badified message.)
Tweet Button (Share the URL with Breaking Badified message.)
Github Star button (https://ghbtns.com/#star)

**Comment by nihey** [comment]
I still haven't found a perfect location to display all these buttons - I think they just don't blend in with the page original design. Maybe putting the in a corner (like the link to github project) would be the best alternative for now.
